### ISSUE TITLE
scMTNI output interpretation

### ISSUE THREAD

**Issue by PrinceZarzees** [Roy-lab/scMTNI#11]
Hello,
I am from Bangladesh University of Engineering and Technology. As for our final year thesis, we are using scMTNI to infer gene regulatory networks. But we are struggling to understand what is the meaning of the value printed beside the edge in the network file. Could you please elaborate a little more about the output format in the README file.

Thank you.
ZARZEES

**Comment by shiluzhang** [comment]
Hi ZARZEES,
Thank you for your interest in scMTNI. The value on the 3rd column is the regression coefficient. You can rank the edges by the absolute value of the coefficient, larger value corresponds to a higher ranking of the edge.
CHP1_cluster1	MECR_cluster1	0.263274
POLR2F_cluster1	SFPQ_cluster1	-0.228401
POLR2L_cluster1	EBNA1BP2_cluster1	0.504227
Interpretation added in README: https://github.com/Roy-lab/scMTNI/blob/master/README.md#additional-note-3-interpretation-of-the-output-file-of-scmtni.

We suggest running scMTNI using the stability selection framework:
1) generate 50 (or more) subsamples of the dataset (https://github.com/Roy-lab/scMTNI#additional-note-1-how-to-generate-subsamples-of-a-given-expression-dataset)
2) run scMTNI on each of the subsamples
3) create a consensus network across the 50 inferred networks (https://github.com/Roy-lab/scMTNI#40-generate-consensus-network-for-subsample-results) 

In the consensus network, the 3rd column is the confidence score ranging from 0 to 1 for each inferred edge. We suggest to keep edges with at least 80% confidence. Example: https://github.com/Roy-lab/scMTNI/blob/master/Results_subsample/analysis/cluster1/consensus_edges.txt



Best,
Shilu
