### ISSUE TITLE
Running scMTNI with subsampling

### ISSUE THREAD

**Issue by PeterZZQ** [Roy-lab/scMTNI#13]
Hi,

I tried to improve the inference accuracy by generating the subsample of the original dataset. I generated a subsample with the command
```
python Scripts/Datasubsample_sc_merged.py --filelist $filelist --indir $indir --nseed 100
```
 but there is no guidance on how to run scMTNI afterwards. Am I supposed to run scMTNI one by one for each subsampled dataset?

**Comment by shiluzhang** [comment]
Hi Peter,
Thank you for your interest in scMTNI. 
Yes, you can run scMTNI one by one for each subsampled dataset using the code in Step 3: https://github.com/Roy-lab/scMTNI#step-3-run. After all the subsamples' networks are generated, you can use this script to create consensus networks across subsamples: https://github.com/Roy-lab/scMTNI#40-generate-consensus-network-for-subsample-results
Please let us know if you have more questions.

Best,
Shilu
