### ISSUE TITLE
In the fifth step of generating the prior network, how are the {sample}_allregulators.txt and ${sample}_allGenes.txt files obtained?

### ISSUE THREAD

**Issue by xudongzhango** [Roy-lab/scMTNI#19]
Thank you very much for providing such a great workflow.I have some questions: Are the {sample}_allregulators.txt and ${sample}_allGenes.txt files extracted from the genes generated in the network in the fourth step?, or are they compiled from other sources?

**Comment by shiluzhang** [comment]
Thank you for your interest in scMTNI. ${sample}_allregulators.txt is generated using the list of known regulators for species of interest (for example, ExampleData/regulators.txt is created using known human regulators). ${sample}_allGenes.txt files are extracted from all of the genes with expression data available per cell type.

**Comment by xudongzhango** [comment]
> Thank you for your interest in scMTNI. ${sample}_allregulators.txt is generated using the list of known regulators for species of interest (for example, ExampleData/regulators.txt is created using known human regulators). ${sample}_allGenes.txt files are extracted from all of the genes with expression data available per cell type.

So is the content of ${sample}_allregulators.txt and ${sample}_allGenes.txt the same for each cell type?

**Comment by shiluzhang** [comment]
The content of ${sample}_allregulators.txt and ${sample}_allGenes.txt are not the same for each cell type. You can start with the common regulators and all genes, and then remove regulators/genes that are not expressed in a particular cell type.

If you follow step 2.3 https://github.com/Roy-lab/scMTNI?tab=readme-ov-file#23-prepare-all-input-files-and-config-file-for-scmtni and use Scripts/PreparescMTNIinputfiles.py with the prepared input files, it will generate ${sample}_allregulators.txt and ${sample}_allGenes.txt.

Below are the number of regulators/genes in the Example data:

wc -l ExampleData/*allGenes.txt 
  237 cluster10_allGenes.txt
   93 cluster1_allGenes.txt
  269 cluster2_allGenes.txt
  176 cluster3_allGenes.txt
  284 cluster6_allGenes.txt
  294 cluster7_allGenes.txt
  269 cluster8_allGenes.txt
  238 cluster9_allGenes.txt

wc -l ExampleData/*allregulators.txt 
  85 cluster10_allregulators.txt
  28 cluster1_allregulators.txt
  88 cluster2_allregulators.txt
  54 cluster3_allregulators.txt
  95 cluster6_allregulators.txt
  96 cluster7_allregulators.txt
  93 cluster8_allregulators.txt
  81 cluster9_allregulators.txt

**Comment by xudongzhango** [comment]
Thank you for your response.
