### ISSUE TITLE
make

### ISSUE THREAD

**Issue by pagarwal14** [Roy-lab/scMTNI#2]
Hi,
I am trying to install the application and when run make from the "Code" dir, I get a message saying "No targets specified and no makefile found."  Indeed I cannot see a makefile in the Code directory.  Please help.
Thanks
Pankaj

**Comment by shiluzhang** [comment]
Hi Pankaj,
Thanks for trying our software! I just added the makefile and a few missing scripts. If you reclone the GitHub repository and reinstall it, it should work now. Please let me know if it still doesn't work. 

Shilu
