### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Chun-Hao025** [Roy-lab/scMTNI#21]
Hi

I tried to run scMTNI on HPC for my dataset in the following code.

`scMTNI -f ./control/testdata_config.txt -x 50 -l ./control/TFs_OGs.txt -n ./gene.txt -d ./lineage_tre
e_for_scMTNI.txt -m ./control/testdata_ogid.txt -s ./control/celltype_order.txt -p 0.2 -b -0.9 -q 0 -c yes` 

And I encounter the following error.

(cluster4|cluster5) p_maintain_edge=0.760605 p_gain=0.760605
(cluster17|cluster4) p_maintain_edge=0.331399 p_gain=0.331399
(cluster7|cluster17) p_maintain_edge=0.411197 p_gain=0.181299
(cluster0|cluster17) p_maintain_edge=0.411197 p_gain=0.229898
(cluster2|cluster7) p_maintain_edge=0.973765 p_gain=0.269504
(cluster8|cluster7) p_maintain_edge=0.973765 p_gain=0.366665
(cluster15|cluster7) p_maintain_edge=0.973765 p_gain=0.337596
(cluster13|cluster8) p_maintain_edge=0.94531 p_gain=0.19614
(cluster12|cluster8) p_maintain_edge=0.94531 p_gain=0.55232
(cluster19|cluster8) p_maintain_edge=0.94531 p_gain=0.196849
(cluster3|cluster13) p_maintain_edge=0.347366 p_gain=0.347366
(cluster9|cluster0) p_maintain_edge=0.689748 p_gain=0.689748
(cluster10|cluster9) p_maintain_edge=0.526863 p_gain=0.526863
(cluster18|cluster10) p_maintain_edge=0.243853 p_gain=0.243853
(cluster11|cluster18) p_maintain_edge=0.571032 p_gain=0.571032
speciesSet.size()=16 Root is cluster5
MappedOrthogroupReader::readSpeciesMapping() --- ./control/celltype_order.txt
MappedOrthogroupReader::readFile - ./control/testdata_ogid.txt
MappedOrthogroupReader::generateGeneOrthoMap()
MetaLearner::init_onefold() read:./control/testdata_config.txt
/home/chun-hao.chao-umw/.lsbatch/1730060068.747730.shell: line 13: 3925602 Segmentation fault      (core dumped) /pi/thomas.fazzio-umw/Chun-Hao/tools/scMTNI/Code/scMTNI -f ./control/testdata_config.txt -x 50 -l ./control/TFs_OGs.txt -n ./gene.txt -d ./lineage_tree_for_scMTNI.txt -m ./control/testdata_ogid.txt -s ./control/celltype_order.txt -p 0.2 -b -0.9 -q 0 -c yes

I spent time on figuring out the error but can't get it. Please give me some possible suggestion on it. Thanks

**Comment by sroyyors** [comment]
hi @Chun-Hao025 is it possible for you to recompile the code? without looking at your specific inputs it is hard for us to tell you the issue. Will you be willing to share this with us?

**Comment by Chun-Hao025** [comment]
Hi
I asked our HPC administrator to help the installation and it works now. Thanks

**Comment by SuvojitHazra** [comment]
That's great to know @Chun-Hao025. Enjoy exploring scMTNI !

Cheers,
Suvojit, RoyLab.
