### ISSUE TITLE
scATACseq_FBS.txt file missing

### ISSUE THREAD

**Issue by pagarwal14** [Roy-lab/scMTNI#3]
Hi,
I have installed the software and was trying to run the example but got an error in the first step about a missing file.

$ Rscript --vanilla Integration/LIGER_scRNAseq_scATAC_FBS.R
Loading required package: cowplot

********************************************************
Note: As of version 1.0.0, cowplot does not change the
  default ggplot2 theme anymore. To recover the previous
  behavior, execute:
  theme_set(theme_cowplot())
********************************************************

Loading required package: Matrix
Loading required package: patchwork

Attaching package: ‘patchwork’

The following object is masked from ‘package:cowplot’:

    align_plots

[1] "Reading sample1"
Error in fread(fname, header = T) : 
  File 'scATACseq_FBS.txt' does not exist or is non-readable. getwd()=='/home/klp/installs/scMTNI'
Execution halted

I looked around the downloaded code but could not find this file.  Please let me know if it exists or if you need to add it to the repo.

Thanks
Pankaj

**Comment by shiluzhang** [comment]
Hi Pankaj,
Sorry for the late reply. I just added the missing files scATACseq.txt and scRNAseq.txt to ExampleData/ and updated the script in Scripts/Integration/LIGER_scRNAseq_scATAC.R. If you reclone the GitHub repository and reinstall it, it should work now. Please let me know if it still doesn't work.

Shilu
