### ISSUE TITLE
Issues Compiling Packages for scMTNI

### ISSUE THREAD

**Issue by Anweshagorantla** [Roy-lab/scMTNI#4]
Hi,
I have cloned the repo and followed the demo instructions until step 3. I am getting  the following error when I run the command included in step 3:

zsh: exec format error: Code/scMTNI

I believe this is because the code was compiled and tested for a Linux environment, but I am trying to run the model on a Mac. I was hoping to recompile the course code locally but ran into some issues. Could you provide me with the commands that I can run to successfully recompile the files locally? Or if there is some other workaround for this please let me know!

Thank you,
Anwesha Gorantla

**Comment by sroyyors** [comment]
hi Anwesha,
The biggest dependency is the GNU scientific library files. You need to download and compile it. Can you do that and then we can update the Makefile to point to your installation.
