### ISSUE TITLE
prior network bed format

### ISSUE THREAD

**Issue by shalberg** [Roy-lab/scMTNI#7]
The prior network function mapMot2Gene.py needs a specific bed format for the peak2gene intersect file mot2peak (e.g. peak2gene file column 4 needs to be a unique peak identifier). The file format specifications are not provided in the documentation.

**Comment by shiluzhang** [comment]
Hi Spencer, thanks for the comments. I have updated the example bed format required by mapMot2Gene.py in https://github.com/Roy-lab/scMTNI/blob/master/Scripts/genPriorNetwork/readme.md. Please let me know if you have other issues with the scripts.
