### ISSUE TITLE
Running method with single cluster

### ISSUE THREAD

**Issue by PeterZZQ** [Roy-lab/scMTNI#8]
Hello,

I wish to run the method with only one cluster in the dataset, may I know how I can set the `celltype_tree_ancestor.txt`. I tried to left the file empty, but it shows the error: 
```
Segmentation fault (core dumped)
```

**Comment by shiluzhang** [comment]
Hi Peter,

Thanks for trying scMTNI! celltype_tree_ancestor.txt file is not needed if there is only one cluster.

In step 3, we add the example command for running one cell cluster with prior or without prior:
https://github.com/Roy-lab/scMTNI#example-usage-of-indep-with-prior-network-indep-single-cell-cluster-version-of-scmtni
`Code/scMTNI -f ExampleData/cluster1_config.txt -x50 -l ExampleData/cluster1_TFs_OGs.txt -n ExampleData/cluster1_AllGenes.txt -m ExampleData/cluster1_ogids.txt -s ExampleData/cluster1.txt  -i yes -c yes -b -0.9 -q 0`

https://github.com/Roy-lab/scMTNI#example-usage-of-indep-without-prior-network-indep-single-cell-cluster-version-of-scmtni
`Code/scMTNI -f ExampleData/cluster1_config_noprior.txt -x50 -l ExampleData/cluster1_TFs_OGs.txt -n ExampleData/cluster1_AllGenes.txt -m ExampleData/cluster1_ogids.txt -s ExampleData/cluster1.txt  -i yes -c yes -b -0.9 -q 0`

Please let me know if it still doesn't work.

Shilu

**Comment by PeterZZQ** [comment]
Yes it works. Thank you!

**Comment by PeterZZQ** [comment]
Hi, when running scMTNI with prior network, should the `-q` be 2 instead of 0 (see the first command above and in the README file)? I try the command above and found that the result is not affected by the prior network anymore.

**Comment by shiluzhang** [comment]
Hi Peter,
Yes, good catch. -q should be set to non-zero for running scMTNI/INDEP with a prior network. You could try q={2,3,4}, a higher value of q will result in prior networks being valued more strongly to select an edge.
I have updated the first command in the README file with `Code/scMTNI -f ExampleData/cluster1_config.txt -x50 -l ExampleData/cluster1_TFs_OGs.txt -n ExampleData/cluster1_AllGenes.txt -m ExampleData/cluster1_ogids.txt -s ExampleData/cluster1.txt  -i yes -c yes -b -0.9 -q 2`.
Thanks!

Best,
Shilu
