### ISSUE TITLE
celltype_tree_ancestor.txt

### ISSUE THREAD

**Issue by mabaoweireadingene** [Roy-lab/scMTNI#9]
How can i generate celltype_tree_ancestor.txt file? Thanks

**Comment by SuvojitHazra** [comment]
Re:  Generating celltype_tree_ancestor.txt file

Thanks for your interest in scMTNI.  You may generate the celltype_tree_ancestor.txt now by following inputs here:

**Point-1**.	First, you make an empty text file named **celltype_tree_ancestor.txt** in text editor (e.g., Vi for Linux, Notepad++ for Windows). Remember the **celltype_tree_ancestor.txt** text file will have **four tab-separated columns**:
•	**_Leftmost column_**: **Child** cell/node. Default value in **string/name**.
•	**_Second leftmost column_**: **Parent** cell/node. Default value in **string/name**.
•	**_Second rightmost column_**: Branch-specific gain rate (The probability that an edge is gained in a child given that the edge is absent in the predecessor cell). The default floating value is **0.2**. 
•	**_Rightmost column_**: Branch-specific loss rate (The probability that an edge is lost in a child given that the edge is present in the predecessor cell). The default floating value is **0.2**. 

**Point-2**.	Check the **Figure** attached. The figure consists of a cell fate transition lineage tree of three types of cells, namely, **Celltype1**, **Celltype2** and **Celltype3**. Theoretically, the tree contains two ancestral parent nodes, namely, **Predecessor cell 1** and **Predecessor cell 2** in cell-state lineage (see, attached **Figure**). Therefore, the tree connections between the three extant cell-types (Celltype1, Celltype2 and Celltype3) can be made using these two parent nodes. Using **Point-1**, the **celltype_tree_ancestor.txt** is made as depicted in attached **Figure**. 

![image](https://github.com/Roy-lab/scMTNI/assets/129977598/9445390a-208b-4d84-b920-84d8a80292c5)



**Please cite this if you use scMTNI:** Zhang, S., Pyne, S., Pietrzak, S., Halberg, S., McCalla, S.G., Siahpirani, A.F., Sridharan, R. and Roy, S., Inference of cell type-specific gene regulatory networks on cell lineages from single cell omic datasets. Nat Commun 14, 3064 (2023). https://doi.org/10.1038/s41467-023-38637-9
